const ERROR_CODES = {
  // Auth Errors
  AUTH_UNAUTHORIZED: 'UNAUTHORIZED',
  AUTH_FORBIDDEN: 'FORBIDDEN',
  AUTH_INVALID_TOKEN: 'INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN: 'EXPIRED_TOKEN',

  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Not Found Errors
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Database Errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // Server Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // AI Service Errors
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
  AI_MODEL_ERROR: 'AI_MODEL_ERROR',
};

const ERROR_MESSAGES = {
  [ERROR_CODES.AUTH_UNAUTHORIZED]: 'Unauthorized access',
  [ERROR_CODES.AUTH_FORBIDDEN]: 'Access forbidden',
  [ERROR_CODES.AUTH_INVALID_TOKEN]: 'Invalid token',
  [ERROR_CODES.AUTH_EXPIRED_TOKEN]: 'Token has expired',
  [ERROR_CODES.VALIDATION_ERROR]: 'Validation error',
  [ERROR_CODES.INVALID_INPUT]: 'Invalid input provided',
  [ERROR_CODES.NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [ERROR_CODES.DATABASE_ERROR]: 'Database error occurred',
  [ERROR_CODES.DUPLICATE_ENTRY]: 'Duplicate entry',
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service unavailable',
  [ERROR_CODES.AI_SERVICE_ERROR]: 'AI service error',
  [ERROR_CODES.AI_MODEL_ERROR]: 'AI model error',
};

const HTTP_STATUS_CODES = {
  [ERROR_CODES.AUTH_UNAUTHORIZED]: 401,
  [ERROR_CODES.AUTH_FORBIDDEN]: 403,
  [ERROR_CODES.AUTH_INVALID_TOKEN]: 401,
  [ERROR_CODES.AUTH_EXPIRED_TOKEN]: 401,
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.INVALID_INPUT]: 400,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.USER_NOT_FOUND]: 404,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.DUPLICATE_ENTRY]: 409,
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.AI_SERVICE_ERROR]: 500,
  [ERROR_CODES.AI_MODEL_ERROR]: 500,
};

module.exports = {
  ERROR_CODES,
  ERROR_MESSAGES,
  HTTP_STATUS_CODES,
};
